#!/usr/bin/env python3
"""Generate skills/index.json and llms.txt from the skills in this repository.

Both files are derived entirely from SKILL.md frontmatter and the on-disk layout, so
they cannot be edited by hand — run this script instead. `--check` regenerates them in
memory and compares byte for byte, which is what keeps a stale catalog out of the
default branch.

Exit status: 0 on success, 1 when --check finds drift.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from validate import parse_frontmatter, split_skill_md  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
SKILLS_DIR = REPO / "skills"
INDEX_PATH = SKILLS_DIR / "index.json"
LLMS_PATH = REPO / "llms.txt"

OWNER = "eventb-rossi"
NAME = "eventb-skill"
REPOSITORY = f"https://github.com/{OWNER}/{NAME}"
RAW_BASE = f"https://raw.githubusercontent.com/{OWNER}/{NAME}/main"
SUMMARY = (
    "Agent skills for developing Event-B formal models as .eventb text and checking "
    "them with the rossi toolchain and eventb-animate."
)
GENERATED_NOTE = "GENERATED by scripts/build_index.py — do not edit; run `make build`."
SCRIPT_SUFFIXES = {".py", ".sh", ".js", ".mjs", ".ts"}


def title_of(path: Path) -> str:
    """The first level-1 heading of a markdown file, or its filename."""
    for line in path.read_text().splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.name


def first_sentence(text: str) -> str:
    flat = " ".join(text.split())
    for end in (". ", "! ", "? "):
        if end in flat:
            return flat[: flat.index(end) + 1].strip()
    return flat


def collect(skill_dir: Path) -> dict:
    frontmatter, _, errors = split_skill_md(skill_dir / "SKILL.md")
    if errors:
        raise SystemExit(f"cannot read {skill_dir / 'SKILL.md'}: {errors[0]}")
    data, parse_errors = parse_frontmatter(frontmatter)
    if parse_errors:
        raise SystemExit(f"cannot parse {skill_dir / 'SKILL.md'}: {parse_errors[0]}")
    metadata = data.get("metadata") or {}

    rel = skill_dir.relative_to(REPO).as_posix()
    references = sorted(
        p.relative_to(REPO).as_posix() for p in (skill_dir / "references").glob("*.md")
    )
    examples = sorted(
        p.relative_to(REPO).as_posix()
        for p in (skill_dir / "examples").iterdir()
        if p.is_dir()
    ) if (skill_dir / "examples").is_dir() else []
    scripts = sorted(
        p.relative_to(REPO).as_posix()
        for p in (skill_dir / "scripts").rglob("*")
        if p.is_file() and p.suffix in SCRIPT_SUFFIXES
    ) if (skill_dir / "scripts").is_dir() else []
    agents = sorted(
        p.relative_to(REPO).as_posix()
        for p in (skill_dir / "agents").glob("*.y*ml")
    ) if (skill_dir / "agents").is_dir() else []

    entry = {
        "name": data["name"],
        "description": data["description"],
        "entry_point": f"{rel}/SKILL.md",
    }
    if version := metadata.get("version"):
        entry["version"] = version
    if license_ := data.get("license"):
        entry["license"] = license_
    if compatibility := data.get("compatibility"):
        entry["compatibility"] = compatibility
    entry["references"] = references
    if examples:
        entry["examples"] = examples
    if scripts:
        entry["scripts"] = scripts
    if agents:
        entry["agents"] = agents
    return entry


def render_index(skills: list[dict]) -> str:
    document = {
        "$comment": GENERATED_NOTE,
        "schema_version": "1.0",
        "name": NAME,
        "description": SUMMARY,
        "repository": REPOSITORY,
        "skills": skills,
    }
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def render_llms(skills: list[dict]) -> str:
    out: list[str] = [f"<!-- {GENERATED_NOTE} -->", "", f"# {NAME}", "", f"> {SUMMARY}", ""]
    out += [
        "## Install",
        "",
        "```sh",
        f"npx skills add {OWNER}/{NAME}",
        "```",
        "",
        "## Prerequisites",
        "",
        "The skill drives two command-line tools and checks for them before modelling:",
        "",
        "- [rossi](https://github.com/eventb-rossi/rossi) 0.1.8+ — parser, static checker,",
        "  formatter and Rodin round-tripping for `.eventb` text.",
        "- [eventb-animate](https://github.com/eventb-rossi/eventb-animate) 6.4+ — ProB-backed",
        "  model checking, well-definedness gates and trace replay. Needs Java 21+.",
        "",
        "## On-demand fetch",
        "",
        "Read a file directly instead of installing the skill:",
        "",
    ]
    for skill in skills:
        out += [f"### {skill['name']}", ""]
        out += [first_sentence(skill["description"]), ""]
        out += [f"- [SKILL.md]({RAW_BASE}/{skill['entry_point']}) — the entry point.", ""]
        if skill["references"]:
            out += ["References:", ""]
            for ref in skill["references"]:
                out.append(f"- [{title_of(REPO / ref)}]({RAW_BASE}/{ref})")
            out.append("")
        if skill.get("examples"):
            out += ["Worked examples:", ""]
            for example in skill["examples"]:
                out.append(
                    f"- [{Path(example).name}]({RAW_BASE}/{example}/README.md) — "
                    f"{title_of(REPO / example / 'README.md')}"
                )
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed files match what would be generated, and fail if not",
    )
    args = parser.parse_args()

    skill_dirs = sorted(d for d in SKILLS_DIR.iterdir() if (d / "SKILL.md").is_file())
    skills = [collect(d) for d in skill_dirs]
    wanted = {INDEX_PATH: render_index(skills), LLMS_PATH: render_llms(skills)}

    if args.check:
        stale = [
            path.relative_to(REPO).as_posix()
            for path, text in wanted.items()
            if not path.exists() or path.read_text() != text
        ]
        if stale:
            print(f"✗ out of date: {', '.join(stale)}")
            print("  run `make build` and commit the result")
            return 1
        print(f"✓ {', '.join(p.relative_to(REPO).as_posix() for p in wanted)} up to date")
        return 0

    for path, text in wanted.items():
        path.write_text(text)
        print(f"wrote {path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
